### ISSUE TITLE
UI Additions

### ISSUE THREAD

**Issue by jakethemartin** [KeetonMartin/gametime#1]
Should show players yet to play as distinct from "active contests"

In order:

Card at top: Active contests
Card in middle: completed contests
Card at bottom: upcoming contests

Additionally: can add a footnote next to players showing % exposure (share of this player across leagues) and whether or not you face this player on an opponent's team anywhere

**Comment by KeetonMartin** [comment]
Resolved by commit ed02234701b9cc4973472933be7f6e7202839e85
